linters:
  enable-all: true
  disable:
    - lll
    - structcheck
    - interfacer
    - nosnakecase
    - scopelint
    - maligned
    - deadcode
    - exhaustivestruct
    - golint
    - varcheck
    - goerr113
    - ifshort
    - rowserrcheck
    - godox
    - sqlclosecheck
    - wastedassign
    - varnamelen
    - wsl
    - nlreturn
    - paralleltest
    - exhaustruct
    - gomnd
    - forcetypeassert
    - wrapcheck
    - tagliatelle
    - dupl
    - funlen
    - testpackage
    - testableexamples
    - depguard
linters-settings:
  cyclop:
    max-complexity: 13
  funlen:
    lines: 70
  stylecheck:
    checks:
      - '-ST1005' # Disable "ST1005: error strings should not be capitalized"
